name: Nest Deploy to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install dependencies
        working-directory: apps/backend
        run: |
          pnpm install --frozen-lockfile
          pnpm prisma generate

      - name: Build app
        working-directory: apps/backend
        run: pnpm build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: chachachat-be-app
          path: apps/backend/dist
          overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: chachachat-be-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_BACKEND_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "chachachat-be"
          slot-name: "Production"
          package: .
