name: Nest Deploy to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --filter cha-cha-chat-be --shamefully-hoist

      - name: Generate Prisma client
        run: npx prisma generate --schema=apps/backend/prisma/schema.prisma

      - name: Build app
        run: pnpm build --filter cha-cha-chat-be

      - name: Zip build output
        run: |
          cd apps/backend
          zip -r ../../backend-build.zip dist node_modules generated

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: backend-build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-build

      - name: Unzip build output
        run: unzip -o deploy/backend-build.zip -d deploy

      - name: Remove zip file
        run: rm deploy/backend-build.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "chachachat-be"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: deploy
