name: Nest Deploy to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --filter @cha-cha-chat/backend

      - name: Build app
        run: pnpm build --filter @cha-cha-chat/backend

      - name: Install @vercel/ncc
        run: npm install -g @vercel/ncc

      - name: Build with @vercel/ncc
        run: ncc build apps/backend/dist/main.js -o apps/backend/dist-ncc

      - name: Zip artifact for upload
        working-directory: apps/backend
        run: zip -r ../../backend-build.zip apps/backend/dist-ncc

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: backend-build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "chachachat-be"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: backend-build.zip
