name: Deploy to Vercel - Preview

on:
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
